---
- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh -

- name: Wait for k3s config to be available
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    timeout: 120

- name: Add k3s config to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
    create: yes
  with_items:
    - "alias k='kubectl'"
    - "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml"
    - "source <(kubectl completion bash)"
    - "complete -o default -F __start_kubectl k"

- name: Apply bashrc changes
  shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Set permissions on kubeconfig
  file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'
