---
- name: Wait for kubectl to be ready
  shell: kubectl get nodes
  register: kubectl_ready
  retries: 10
  delay: 5
  until: kubectl_ready.rc == 0

- name: Apply guacamole manifest
  command: kubectl apply -f "{{ role_path }}/files/guacamole.yml"
