apiVersion: v1
kind: Namespace
metadata:
  name: guacamole
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
  namespace: guacamole
data:
  guacamole.properties: |
    guacd-hostname=guacd
    guacd-port=4822
    postgresql-hostname=postgres
    postgresql-port=5432
    postgresql-database=guacamole_db
    postgresql-username=guacamole
    postgresql-password=guacamole
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: guacamole
spec:
  selector:
    app: guacd
  ports:
    - protocol: TCP
      port: 4822
      targetPort: 4822
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: guacamole
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
spec:
  selector:
    app: guacamole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: guacamole
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/crownlabs/PROJECT/guacamole/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
      - name: guacd
        image: harbor.crownlabs.polito.it/sid/guacd:1.5.5
        imagePullPolicy: Always
        command: ["/usr/local/sbin/guacd"]
        args: ["-b", "0.0.0.0", "-f"]
        ports:
        - containerPort: 4822
        volumeMounts:
        - name: drive
          mountPath: /drive
        - name: record
          mountPath: /record
      volumes:
      - name: drive
        hostPath:
          path: /home/crownlabs/PROJECT/guacamole/drive
      - name: record
        hostPath:
          path: /home/crownlabs/PROJECT/guacamole/record
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/guacamole
        - name: POSTGRES_DB
          value: guacamole_db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-scripts
        hostPath:
          path: /home/crownlabs/PROJECT/db/init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: harbor.crownlabs.polito.it/sid/guacamole:1.5.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: guacamole-config
          mountPath: /usr/local/tomcat/.guacamole/guacamole.properties
          subPath: guacamole.properties
        - name: drive
          mountPath: /drive
      volumes:
      - name: guacamole-config
        configMap:
          name: guacamole-config
      - name: drive
        hostPath:
          path: /home/crownlabs/PROJECT/guacamole/drive
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: guacamole
type: Opaque
data:
  POSTGRES_USER: Z3VhY2Ftb2xl
  POSTGRES_PASSWORD: Z3VhY2Ftb2xl